java:
  name: java
  description: False
  cover: False
spring:
  name: spring
  description: False
  cover: False
database:
  name: database
  description: False
  cover: False
interview:
  name: interview
  description: False
  cover: False
os:
  name: os
  description: False
  cover: False

###############################################################
# 원본 태그
#
# speeches:
#   name: speeches
#   description: Some of the greatest words ever spoken.
#   cover: assets/images/speeches.jpg
# fiction:
#   name: fiction
#   description: False
#   cover: False
# fables:
#   name: fables
#   description: A series of short stories that make you think.
#   cover: assets/images/fables.jpg
# getting-started:
#   name: getting-started
#   description: False
#   cover: False
###############################################################
